### ISSUE TITLE
Why not just nproc?

### ISSUE THREAD

**Issue by idealo-ricardo-band** [SimenB/github-actions-cpu-cores#36]
```shell
$ nproc --help
Usage: nproc [OPTION]...
Print the number of processing units available to the current process,
which may be less than the number of online processors
```

Works perfectly fine in a simple shell step.

```yaml
- name: Get core count
  id: nproc
  run: echo "cores=$(nproc --all)" >> $GITHUB_OUTPUT
- name: Using nproc directly
  run: terraform plan -parallelism=$(nproc --all)
```

Why would I use your action instead? I don't see the benefit, but am curious for your use case. I mean this only works on Linux and macOS and a js based action would also run on Windows. On the other hand the js based action is like 3000 lines of code and a js engine needs to start up. ;)
